title: Embroidermodder 2.0
description: Free and Open Source Software for Machine Embroidery
show_downloads: true
markdown: GFM
theme: jekyll-theme-minimal

collections:
  tutorials:
    order:
      add_a_single_stitch.md
