name: build Mac OS

on:
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * *"

jobs:
  build-macos-latest:
    runs-on: macos-latest
    steps:
      - name: build
        run:
          git clone http://github.com/embroidermodder/libembroidery
          cmake libembroidery
          cmake --build .
