name: Main Script

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "15 3 * * *"

env:
  needle_ver: embroidermodder/website/.github/workflows/needle.yml@v1.0.0

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    uses: ${{ needle_ver }}
    with:
      os: ubuntu-latest
      flags: --linux --update

  build-test-macos:
    runs-on: macos-latest
    uses: ${{ needle_ver }}
    with:
      os: macos-latest
      flags: --macos --update

  build-test-windows:
    runs-on: windows-latest
    uses: ${{ needle_ver }}
    with:
      os: windows-latest
      flags: --windows --update

  code-quality:
    runs-on: ubuntu-latest
    uses: ${{ needle_ver }}
    with:
      os: ubuntu-latest
      flags: --code-quality --update

  build-website:
    runs-on: ubuntu-latest
    uses: ${{ needle_ver }}
    with:
      os: ubuntu-latest
      flags: --website
    steps:
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build-website
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

