name: Build GNU/Linux

on:
  workflow_dispatch:
  schedule:
    - cron: "15 5 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          git clone https://github.com/embroidermodder/embroideryMobile
          cmake embroideryMobile
          cmake --build .
