name: Main Script

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "15 3 * * *"

env:
  needle_ver: 7602116ef97ad9521d6bd0fa24efa6d056bd9382

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: build-test
      uses: embroidermodder/website/.github/workflows/needle.yml@${{ needle_ver }}
      with:
        os: ${{ matrix.os }}
        flags: --${{ matrix.os }} --update

  code-quality:
    runs-on: ubuntu-latest
    steps:
    - name: code-quality
      uses: embroidermodder/website/.github/workflows/needle.yml@${{ needle_ver }}
      with:
        os: ubuntu-latest
        flags: --code-quality --update

  build-website:
    runs-on: ubuntu-latest
    steps:
    - name: build
      uses: embroidermodder/website/.github/workflows/needle.yml@${{ needle_ver }}
      with:
        os: ubuntu-latest
        flags: --website
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build-website
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

