name: build GNU/Linux

on:
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * *"

jobs:
  build-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run:
          git clone http://github.com/embroidermodder/libembroidery
          cmake libembroidery
          cmake --build .
