name: Main Script

on:
  workflow_dispatch:
  #push:
  #schedule:
  #  - cron: "15 3 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-test-linux:
    uses: embroidermodder/website/.github/workflows/needle.yml@v1.1.0
    with:
      name: build_test_linux
      os: ubuntu-latest
      flags: --linux --update

  build-test-macos:
    uses: embroidermodder/website/.github/workflows/needle.yml@v1.1.0
    with:
      name: build_test_macos
      os: macos-latest
      flags: --macos --update

  build-test-windows:
    uses: embroidermodder/website/.github/workflows/needle.yml@v1.1.0
    with:
      name: build_test_windows
      os: windows-latest
      flags: --windows --update

  code-quality:
    uses: embroidermodder/website/.github/workflows/needle.yml@v1.1.0
    with:
      name: code_quality
      os: ubuntu-latest
      flags: --code-quality --update

  build-website:
    runs-on: ubuntu-latest
    steps:
    - uses: embroidermodder/website/.github/workflows/needle.yml@v1.1.0
      with:
        name: website
        os: ubuntu-latest
        flags: --website
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build-website
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

