name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docs:
    name: "Build Reference Manual"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build"
        run: bash bin/build_refman.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./refman.pdf
