name: Docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    name: "Build Reference Manual"
    runs-on: ubuntu-latest
    steps:
      - name: "Build"
        run: |
          git clone https://github.com/embroidermodder/libembroidery
          cd libembroidery
          bash bin/build_refman.sh
          cd ..
