name: Test libembroidery

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    name: "Build on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test
        run: |
          git clone https://github.com/embroidermodder/libembroidery
          cd libembroidery
          mkdir build
          cd build
          cmake ..
          cmake --build .
          ./embroider --test
