name: Website

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "15 3 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build
      run: bash bin/package.sh

    - uses: actions/upload-artifact@v4
      with:
        name: pages
        path: artifact.tar

  deploy:
    needs: build-website
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

