name: Website

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "15 3 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-website:
    uses: embroidermodder/needle/.github/workflows/needle.yml@v1.6
    with:
      name: github-pages
      path: artifact.tar
      os: ubuntu-latest
      flags: --website

  deploy:
    needs: build-website
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

